### ISSUE TITLE
Sample doesn't match what's on the article?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [StylingAndroid/BottomNavBar#1]
All I see is a simple BottomNavBar. Nothing special at all... Not animation anywhere...

**Comment by StylingAndroid** [comment]
Fixed.

**Comment by AndroidDeveloperLB** [comment]
@StylingAndroid Seems better.

However, importing the project itself goes quite wrong. This is what I get when I first clone and open it:

![image](https://user-images.githubusercontent.com/5357526/68108825-9e6c9380-fef1-11e9-80de-6bce284594ed.png)
